---
:concurrency: 5
production:
  # Redis we are using; it has connection limit 20; and we are using 1 server to process the data
  :concurrency: 1
  # Set timeout to 8 on Heroku, longer if you manage your own systems.
  :timeout: 8
  :logfile: ./log/sidekiq.log
